sort:
  by: filename

nav:
  - Overview: 
    - index.md

  - What is Ncut?: placeholder.md

  - How Ncut Works:
    - methods/*.md

  - Tutorials (basic): 
    - tutorials/index.md
    - tutorials/01_tutorials.md
    - tutorials/02_discrete_ncut.md
    - tutorials/03_hierarchy_ncut.md
  
  - Tutorials (advanced):
    - Feature Alignment: tutorials/05_feature_alignment.md
    - Custom Model: tutorials/06_own_model.md
    # - tutorials/07_parameters.md

  - Tutorials (miscs):
    - Gradient of NCUT: gradient_of_ncut.md
    - Add Nodes: tutorials/08_add_nodes.md
    - Mixing Resolutions: tutorials/09_mixing_data.md
    - Channel Tracing: tutorials/04_channel_tracing.md

  - Usage Examples:
    - Gallery - Model: gallery.md
    - Gallery - Dataset: gallery/gallery_dataset.md

  - Blogs:
    - Aligned NCUT: alignedcut_vs_ncut.md
  
  - API References: api_reference.md
  