sort:
  by: filename

nav:
  - Overview: 
    - index.md

  - What is Ncut?: what_is_ncut.md

  - How Fast is Ncut?: how_fast_is_ncut.md

  - Tutorials: 
    - tutorials/01_tutorials.md
    - tutorials/02_discrete_ncut.md
    - tutorials/03_hierarchy_ncut.md

  - How Ncut Works:
    - methods/*.md
  
  - Tutorials (advanced):
    - Feature Alignment: tutorials/feature_alignment.md
    - Custom Model: tutorials/custom_model.md
    - tutorials/inference_extrapolation.md

  - Tutorials (miscs):
    - tutorials/gradient_of_ncut.md
    - tutorials/channel_tracing.md
    - tutorials/mixing_resolution.md

  - Usage Examples:
    - Model Gallery: usage_examples/model_gallery.md
    - Out-of-Distribution Adaptation: usage_examples/ood_adaptation.md

  - Blogs:
    - blogs/*.md
  
  - API References: api/api_reference.md
  