sort:
  by: filename

nav:
  - Overview: 
    - index.md

  - What is Ncut?: what_is_ncut.md

  - How Fast is Ncut?: how_fast_is_ncut.md

  - How Ncut Works:
    - methods/*.md
  
  - Tutorials: 
    - tutorials/01_tutorials.md
    - tutorials/02_discrete_ncut.md
    - tutorials/03_hierarchy_ncut.md
  
  - Tutorials (misc):
    - Feature Alignment: tutorials/feature_alignment.md
    - Custom Model: tutorials/custom_model.md
    - tutorials/inference_extrapolation.md
    - tutorials/gradient_of_ncut.md
    - tutorials/channel_tracing.md
    - tutorials/mixing_resolution.md

  - Examples:
    - Multi-scale Clustering: https://github.com/huzeyann/ncut_pytorch/blob/master/examples/summary.ipynb
    - Single-scale Clustering: https://github.com/huzeyann/ncut_pytorch/blob/master/examples/generate.ipynb
    - Inference Time: https://github.com/huzeyann/ncut_pytorch/blob/master/examples/predictor.ipynb
    - Interactive Preview: https://github.com/huzeyann/ncut_pytorch/blob/master/examples/preview.ipynb

  - Blogs:
    - blogs/*.md
    - Model Gallery: usage_examples/model_gallery.md
    - Out-of-Distribution Adaptation: usage_examples/ood_adaptation.md
  
  - API References: api/api_reference.md
  
